name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Commit dist
        if: github.event_name == 'push'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -f dist
          if ! git diff --cached --quiet; then
            git commit -m "chore: add build output" && git push
          fi
      - name: Publish preview
        if: github.event_name == 'pull_request'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          TRUSTED_CONTRIBUTORS: ${{ secrets.TRUSTED_CONTRIBUTORS }}
        run: |
          IFS=',' read -r -a trusted_contributors_array <<< "$TRUSTED_CONTRIBUTORS"
          is_trusted=false
          for contributor in "${trusted_contributors_array[@]}"; do
            if [[ "$contributor" == "$PR_AUTHOR" ]]; then
              is_trusted=true
              break
            fi
          done
          if [[ "$is_trusted" == false ]]; then
            echo "User $PR_AUTHOR is not a trusted contributor. Skipping npm publish."
            exit 0
          fi
          VERSION=$(node -p "require('./package.json').version")
          npm version "$VERSION-pr.$PR_NUMBER.$GITHUB_RUN_NUMBER" --no-git-tag-version
          npm publish --tag "pr-$PR_NUMBER"
      - name: Release
        if: github.event_name == 'push'
        uses: cycjimmy/semantic-release-action@v3
        with:
          branches: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

