name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm test
      - name: Commit dist
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add dist
          if ! git diff --cached --quiet; then
            git commit -m "chore: add build output" && git push
          fi
      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          branches: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

